import DocsLayout from "@/layouts/DocsLayout";
import Image from "next/image";

const Docs = () => {
  const navMenu = {
    name: "Art Generator",
    menu: [
      {
        url: "/docs/art-generator",
        label: "Introduction",
      },
      {
        url: "/docs/art-generator/getting-started",
        label: "Getting Started",
      },
      {
        url: "/docs/art-generator/uploading-artwork-and-metadata",
        label: "Uploading Artwork and Metadata",
        anchorMenu: [
          {
            anchor: "upload-your-files",
            label: "Upload Your Files",
          },
          {
            anchor: "upload-progress",
            label: "Upload Progress",
          },
          {
            anchor: "page-selection",
            label: "Page Selection",
          },
        ],
      },
      {
        url: "/docs/art-generator/art-generator-dashboard",
        label: "Art Generator Dashboard",
      },
      {
        url: "/docs/art-generator/generate-dashboard",
        label: "Generate Dashboard",
        anchorMenu: [
          {
            anchor: "editing traits and rarity",
            label: "Editing Traits and Rarity",
          },
          {
            anchor: "rules",
            label: "Rules",
          },
          {
            anchor: "rules modal",
            label: "Rules Modal",
          },
          {
            anchor: "adding custom image",
            label: "Adding Custom Image",
          },
          {
            anchor: "custom image modal",
            label: "Custom Image Modal",
          },
          {
            anchor: "custom edit page",
            label: "Custom Edit Page",
          },
          {
            anchor: "live rarity configuration",
            label: "Live Rarity Configuration",
          },
          {
            anchor: "hidden traits ",
            label: "Hidden Traits ",
          },
        ],
      },
      {
        url: "/docs/art-generator/edit-page",
        label: "Edit Page",
      },
      {
        url: "/docs/art-generator/contract",
        label: "Contract",
      },
      {
        url: "/docs/art-generator/settings",
        label: "Settings",
      },
    ],
  };

  return (
    <DocsLayout navMenu={navMenu}>
      <h2>Generate Dashboard</h2>
      <div className="space-y-12">
        <p>The Generate Dashboard empowers you with a variety of tools to fine-tune your NFT collection:</p>

        <div className="space-y-5">
          <h3>Editing Traits and Rarity</h3>
          <p>
            Modify traits and rarity settings to achieve the desired artistic and rarity characteristics in your NFTs.
          </p>
          <Image
            src="/images/docs/art-generator-generator-dashboard-1.png"
            width="700"
            height="700"
            alt="Docs"
            className="w-[676px] rounded"
          />
          <Image
            src="/images/docs/art-generator-generator-dashboard-2.png"
            width="700"
            height="700"
            alt="Docs"
            className="w-[676px] rounded"
          />
        </div>

        <div className="space-y-5">
          <h3>Rules</h3>
          <p>
            Users will create a rule if they want to see what assets will be mixed with or what assets will not mix with
            others assets that can be generated by the app. If the user wants to create a rule, they simply click the
            “Create rule” button on Rules tab.
          </p>
          <Image
            src="/images/docs/art-generator-generator-dashboard-3.png"
            width="700"
            height="700"
            alt="Docs"
            className="w-[676px] rounded"
          />
        </div>

        <div className="space-y-5">
          <h3>Rules Modal</h3>
          <p>
            A modal will show, and the user will be prompted on what assets they want to create a rule. Users can select
            the rule type which can be &quot;Only mix with,&quot; &quot;Doesn&apos;t mix with,&quot; or &quot;Always
            pair with&quot; the other trait.
          </p>
          <p>
            Once the user is done configuring the rules, they will select the “Save Rule” button to save their created
            rule.
          </p>
          <Image
            src="/images/docs/art-generator-generator-dashboard-4.png"
            width="700"
            height="700"
            alt="Docs"
            className="w-[676px] rounded"
          />
          <Image
            src="/images/docs/art-generator-generator-dashboard-5.png"
            width="700"
            height="700"
            alt="Docs"
            className="w-[676px] rounded"
          />
          <Image
            src="/images/docs/art-generator-generator-dashboard-6.png"
            width="700"
            height="700"
            alt="Docs"
            className="w-[676px] rounded"
          />
        </div>

        <div className="space-y-5">
          <h3>Adding Custom Images</h3>
          <p>Include custom images to further personalize your NFT collection.</p>
          <ul className="list list-disc list-inside">
            <li>Users can upload a unique image on the that will be included in the generated art.</li>
            <li>
              By clicking the box that has a dash stroke, users can upload the image they want to include in their
              generated art. This part is on the “Custom image” tab.
            </li>
          </ul>
          <Image
            src="/images/docs/art-generator-generator-dashboard-7.png"
            width="700"
            height="700"
            alt="Docs"
            className="w-[676px] rounded"
          />
        </div>

        <div className="space-y-5">
          <h3>Custom Image Modal</h3>
          <p>
            Once the user successfully picks the image that they want to include, a modal will show, and the user can
            configure the following forms like the name of the uploaded item and if the user wants to add “custom
            attributes” they can input it, and they can also delete it if they added some custom attributes. Lastly,
            they can add the Metadata description on their uploaded image.
          </p>
          <p>
            Once the user was done configuring it, they will click the “Save image” button, and the uploaded item will
            be saved.
          </p>
          <Image
            src="/images/docs/art-generator-generator-dashboard-8.png"
            width="700"
            height="700"
            alt="Docs"
            className="w-[676px] rounded"
          />
        </div>

        <div className="space-y-5">
          <h3>Custom Image Edit Page</h3>
          <p>
            This is the UI when users added or uploaded a Custom Image. Users can upload another image by clicking the
            “Upload” button. If there is an image uploaded, users can edit the image, duplicate, or delete the uploaded
            image as well.
          </p>
          <Image
            src="/images/docs/art-generator-generator-dashboard-9.png"
            width="700"
            height="700"
            alt="Docs"
            className="w-[676px] rounded"
          />
        </div>

        <div className="space-y-5">
          <h3>Live Rarity Configuration</h3>
          <p>Adjust live rarity settings to reflect the rarity of your NFTs dynamically.</p>
          <Image
            src="/images/docs/art-generator-generator-dashboard-10.png"
            width="700"
            height="700"
            alt="Docs"
            className="w-[676px] rounded"
          />
        </div>

        <div className="space-y-5">
          <h3>Hidden Traits Management</h3>
          <p>Add or remove hidden traits to introduce an element of mystery to your NFT collection.</p>
          <Image
            src="/images/docs/art-generator-generator-dashboard-11.png"
            width="700"
            height="700"
            alt="Docs"
            className="w-[676px] rounded"
          />
        </div>

        <div className="space-y-5">
          <h3>Ranking by Rarity</h3>
          <p>
            Assign ranks to your NFTs based on their rarity to create a hierarchical structure within your collection.
          </p>
          <Image
            src="/images/docs/art-generator-generator-dashboard-12.png"
            width="700"
            height="700"
            alt="Docs"
            className="w-[676px] rounded"
          />
        </div>

        <div className="space-y-5">
          <h3>Filter Customization</h3>
          <p>Add and edit filters to refine the way your NFTs are displayed in the collection.</p>
          <Image
            src="/images/docs/art-generator-generator-dashboard-13.png"
            width="700"
            height="700"
            alt="Docs"
            className="w-[676px] rounded"
          />
        </div>

        <div className="space-y-5">
          <h3>Edit Token Dashboard</h3>
          <p>
            To be able to see this UI, users can select one of the generated art, and this interface will show. If they
            select the generated art, they can be able to edit or configure it by the traits that are included in the
            following. They can also change traits in the app generated. Users can view it full screen also by clicking
            the image.
          </p>
          <Image
            src="/images/docs/art-generator-generator-dashboard-14.png"
            width="700"
            height="700"
            alt="Docs"
            className="w-[676px] rounded"
          />
          <Image
            src="/images/docs/art-generator-generator-dashboard-15.png"
            width="700"
            height="700"
            alt="Docs"
            className="w-[676px] rounded"
          />
          <Image
            src="/images/docs/art-generator-generator-dashboard-16.png"
            width="700"
            height="700"
            alt="Docs"
            className="w-[676px] rounded"
          />
        </div>
      </div>
    </DocsLayout>
  );
};

export default Docs;
